/**
 * APPLICATION DTO: PurchaseDTO
 * Converts between domain entity ↔ API payload shapes.
 */
export class PurchaseDTO {
  /** Domain Purchase → API save payload */
  static toSavePayload(purchase) {
    return {
      PurchaseDate: purchase.purchaseDate,
      PurchaseNo: purchase.purchaseNo,
      DueDate: purchase.dueDate,
      PurchaseType: purchase.purchaseType,
      SupplierId: purchase.supplierId,
      InvoiceNo: purchase.invoiceNo,
      InvoiceDate: purchase.invoiceDate,
      InvoiceAmt: purchase.invoiceAmt,
      Remarks: purchase.remarks,
      TaxMode: purchase.taxMode,
      IGSTBill: purchase.igst,
      TCSPercent: purchase.tcsPercent,
      TCSAmt: purchase.tcsAmt,
      GrossAmt: purchase.grossAmt,
      TransAmt: purchase.transAmt,
      CDAmt: purchase.cdAmt,
      DiscAmt: purchase.discAmt,
      CESSAmt: purchase.cessAmt,
      CGSTAmt: purchase.cgstAmt,
      SGSTAmt: purchase.sgstAmt,
      IGSTAmt: purchase.igstAmt,
      GSTAmt: purchase.gstAmt,
      OtherPlus: purchase.otherPlus,
      OtherSub: purchase.otherSub,
      NetAmt: purchase.netAmt,
      Loadding: purchase.loadding,
      LorryNo: purchase.lorryNo,
      PurchaseDetails: purchase.items.map(PurchaseDTO.itemToPayload),
    };
  }

  /** Domain PurchaseItem → detail row payload */
  static itemToPayload(item) {
    return {
      PDId: item.id,
      ProductCode: item.productCode,
      ProductName: item.productName,
      ProductRefId: item.productRefId,
      HSNCode: item.hsnCode,
      UOM: item.uom,
      UOMRefid: item.uomRefId,
      MRP: item.mrp,
      PurchaseRate: item.purchaseRate,
      LandingCost: item.landingCost,
      ItemQty: item.itemQty,
      FreeQty: item.freeQty,
      CDPercent: item.cdPercent,
      CDAmount: item.cdAmount,
      DiscountPercent: item.discountPercent,
      DiscountAmt: item.discountAmt,
      TaxPercent: item.taxPercent,
      TaxAmt: item.taxAmt,
      CESSPer: item.cessPercent,
      CESSAmount: item.cessAmount,
      TransPer: item.transPercent,
      TransAmt: item.transAmt,
      SaleRate: item.saleRate,
      Amount: item.amount,
      BatchNo: item.batchNo,
      MfgDate: item.mfgDate,
      ExpiryDate: item.expiryDate,
      StockQty: item.stockQty,
      Narration: item.narration,
    };
  }

  /** API response → domain Purchase shape */
  static fromApiResponse(data) {
    return {
      id: data.Id || data.id || 0,
      purchaseNo: data.PurchaseNo || '',
      purchaseDate: data.PurchaseDate || '',
      dueDate: data.DueDate || '',
      purchaseType: data.PurchaseType || 'Purchase',
      supplierId: data.SupplierId || 0,
      supplierName: data.SupplierName || '',
      invoiceNo: data.InvoiceNo || '',
      invoiceDate: data.InvoiceDate || '',
      invoiceAmt: data.InvoiceAmt || 0,
      remarks: data.Remarks || '',
      taxMode: data.TaxMode || 'exclusive',
      igst: data.IGSTBill || false,
      tcsPercent: data.TCSPercent || 0,
      grossAmt: data.GrossAmt || 0,
      transAmt: data.TransAmt || 0,
      cdAmt: data.CDAmt || 0,
      discAmt: data.DiscAmt || 0,
      cessAmt: data.CESSAmt || 0,
      cgstAmt: data.CGSTAmt || 0,
      sgstAmt: data.SGSTAmt || 0,
      igstAmt: data.IGSTAmt || 0,
      gstAmt: data.GSTAmt || 0,
      otherPlus: data.OtherPlus || 0,
      otherSub: data.OtherSub || 0,
      netAmt: data.NetAmt || 0,
      loadding: data.Loadding || '',
      lorryNo: data.LorryNo || '',
      items: (data.PurchaseDetails || []).map(d => ({
        id: d.PDId || 0,
        rowId: crypto.randomUUID(),
        productCode: d.ProductCode || '',
        productName: d.ProductName || '',
        productRefId: d.ProductRefId || 0,
        hsnCode: d.HSNCode || '',
        uom: d.UOM || '',
        uomRefId: d.UOMRefid || 0,
        mrp: d.MRP || 0,
        purchaseRate: d.PurchaseRate || 0,
        landingCost: d.LandingCost || 0,
        itemQty: d.ItemQty || 0,
        freeQty: d.FreeQty || 0,
        cdPercent: d.CDPercent || 0,
        cdAmount: d.CDAmount || 0,
        discountPercent: d.DiscountPercent || 0,
        discountAmt: d.DiscountAmt || 0,
        taxPercent: d.TaxPercent || 0,
        taxAmt: d.TaxAmt || 0,
        cessPercent: d.CESSPer || 0,
        cessAmount: d.CESSAmount || 0,
        transPercent: d.TransPer || 0,
        transAmt: d.TransAmt || 0,
        saleRate: d.SaleRate || 0,
        amount: d.Amount || 0,
        batchNo: d.BatchNo || '',
        mfgDate: d.MfgDate || '',
        expiryDate: d.ExpiryDate || '',
        stockQty: d.StockQty || 0,
        narration: d.Narration || '',
        editMode: false,
      })),
    };
  }
}
